# Generated by Django 4.1.5 on 2023-01-27 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flight",
            name="provider",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
