# Generated by Django 4.1.5 on 2023-01-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="flight_number",
            field=models.CharField(max_length=15),
        ),
    ]
